language: node_js
node_js:
  - 9
script:
  - 'npm run test:lint'
  - npm run build
  - polymer test --module-resolution=node --npm --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    secure: NROXIT6jN4cCo2ny9wcZf0JKxxg5gTOvnch8iorbd0Jq80GMfaIuTprAA6ztncayEMgJrmwKPuduolAjwNe9h+p42d3u3bDq/BKtJ5/gOLBmd97F2SmSY0C0AgdO8mrvq4tLrUutlAzvaziVD1gW2pmaZO6x3e33IKBPxPvuUAk=
env:
  global:
    SAUCE_USERNAME: Desire2Learn

